### ISSUE TITLE
kitchen inspec-shell default-ubuntu-1404

### ISSUE THREAD

**Issue by srenatus** [inspec/kitchen-inspec#36]
I often find myself looking up the ssh command-line parameters used in `kitchen login [instance]` to run `inspec shell` against it. Wouldn't it be great if this could be easier?

**Comment by chris-rock** [comment]
+1 same here ... Maybe we add a command to kitchen like 'kitchen inspec` to open an inspec shell.

**Comment by srenatus** [comment]
`kitchen inspec` would be great, too, just a little ambiguous.

**Comment by chris-rock** [comment]
or we could name it `kitchen inspec-shell`

**Comment by srenatus** [comment]
+1 `kitchen inspec` (Is this kind of extension possible at all?)

**Comment by adamleff** [comment]
kitchen-inspec could not itself add this command as the command list in TK is not pluggable. However, it might be a reasonable change to support an inspec shell command in TK as long as the instance in question has a verifier of `kitchen-inspec`. I can talk to the TK maintainers about this. Leaving this issue open for now for tracking.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
